version: "2.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    environment:
      TEST_DB_HOST: postgres
      TEST_CONSUL_URL: http://consul:8500
    links:
      - postgres
      - consul

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  consul:
    image: consul:0.7.5
    command: agent -dev -client 0.0.0.0 -datacenter inst-jobs-dev -node inst-jobs-consul -bootstrap
    environment:
      GOMAXPROCS: "2"
      VIRTUAL_PORT: 8500

